### ISSUE TITLE
ai vậy

### ISSUE THREAD

**Issue by minhharry** [clgslsm/ktlt_btl_2#1]

**Comment by clgslsm** [comment]
Sorry bro. Tại lỡ thấy nên tải về mà quên xin bro. Sorri nha 😥😥😥.

**Comment by minhharry** [comment]
ông thấy ở đâu hay ai đưa cho ông link vậy

**Comment by clgslsm** [comment]
Ừm có phải Minh học ptnk ko nhể. Bữa ngồi chung với Kiệt Đặng thấy dò cả ngàn test case nên tính xin Kiệt Đặng test chung. Rồi Kiệt Đặng cho cái link này ấy. Cho mk xin lỗi nhá 😔😔😔.

**Comment by minhharry** [comment]
Yes, add zalo t phát :))), 0938652497
